# Generated by Django 5.2 on 2026-05-22 12:29

import django.db.models.deletion
import shipments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(default=shipments.models.generate_tracking_number, max_length=20, unique=True)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_phone', models.CharField(max_length=20)),
                ('sender_address', models.TextField()),
                ('sender_city', models.CharField(max_length=100)),
                ('sender_postal', models.CharField(max_length=20)),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_email', models.EmailField(max_length=254)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('receiver_address', models.TextField()),
                ('receiver_city', models.CharField(max_length=100)),
                ('receiver_postal', models.CharField(max_length=20)),
                ('cargo_type', models.CharField(choices=[('documents', 'Documents'), ('fragile', 'Fragile Items'), ('perishable', 'Perishable Goods'), ('electronics', 'Electronics'), ('furniture', 'Furniture'), ('machinery', 'Machinery'), ('other', 'Other')], max_length=20)),
                ('cargo_description', models.TextField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cargo_type_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('booked', 'Booked'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('booked', 'Booked'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20)),
                ('message', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='shipments.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
